version: "3"
services:
  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      PORT: ${APPLICATION_PORT}
    depends_on:
      - mongo
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      MONGO_URI: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@mongo:27017/${MONGO_WORKER_DB_NAME}?authSource=admin
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@mongo:27017/
