version: "3"
services:
  traefik:
    image: traefik
    container_name: traefik-proxy
    restart: always
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      PORT: ${APPLICATION_PORT}
    depends_on:
      - mongo
    # ports:
    # - ${APPLICATION_PORT}:${APPLICATION_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=${APPLICATION_PORT}"

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      MONGO_URI: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@mongo:27017/${MONGO_WORKER_DB_NAME}?authSource=admin
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    # ports:
    # - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@mongo:27017/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongoexpress.rule=Host(`mongo-express.localhost`)"
      - "traefik.http.routers.mongoexpress.entrypoints=web"
      - "traefik.http.services.mongoexpress.loadbalancer.server.port=8081"
